### ISSUE TITLE
Example about Image dataset

### ISSUE THREAD

**Issue by meet-minimalist** [theblackcat102/H5Record#1]
Thanks for your work. Do you have an end to end example about image dataset which includes creating h5records file similar to tfrecord files and then using it in dataloader mechanism just like tf dataset api loader mechanism?

**Comment by theblackcat102** [comment]
@meet-minimalist You can checkout this [simple mnist example](https://github.com/theblackcat102/H5Record/blob/main/test/example.py) for image classification.

**Comment by xuhangc** [comment]
@theblackcat102 Hi. Based on the example, do all images have uniform shape in order to be converted to h5py?
